name: $(Date:yyyyMMdd)$(Rev:.rr)

variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - /.dependabot/*
      - /.poshchan/*
      - /.github/**/*
      - /.vscode/**/*
      - /.vsts-ci/misc-analysis.yml
      - /tools/**/*
      - .editorconfig
      - .gitattributes
      - .gitignore
      - /docs/**/*
      - /CHANGELOG.md
      - /CONTRIBUTING.md
      - /README.md
      - /LICENSE.txt
      - /CODE_OF_CONDUCT.md

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: BuildAndSign
  displayName: Build and Sign
  jobs:
  - job: 'BuildAndSign'
    variables:
    - group: ESRP
    displayName: Build and Sign
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        includePreviewVersions: true
        version: 6.x
    - powershell: |
        Get-ChildItem -Path env:
      displayName: Capture environment
      condition: succeededOrFailed()
    - pwsh: |
        # build agents get reused so we make sure to remove the old archive
        Remove-Item -Path $(Build.SourcesDirectory)/SignedZip -Recurse -Force -ErrorAction Ignore
        Remove-Item -Path $(Build.SourcesDirectory)/out -Recurse -Force -ErrorAction Ignore
        Remove-Item -Path $(Build.SourcesDirectory)/signed -Recurse -Force -ErrorAction Ignore
        .\build.ps1 -Clean
        Remove-Item .\out\*.pdb
        $packageVersion = (Import-PowerShellDataFile $(Build.SourcesDirectory)/out/Microsoft.PowerShell.TextUtility/Microsoft.PowerShell.TextUtility.psd1).ModuleVersion
        $vstsCommandString = "vso[task.setvariable variable=PackageVersion]$packageVersion"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"
      displayName: Build
    - publish: "out/"
      artifact: out

    - template: EsrpSign.yml@ComplianceRepo
      parameters:
        # the folder which contains the binaries to sign
        buildOutputPath: $(Build.SourcesDirectory)/out
        # the location to put the signed output
        signOutputPath: $(Build.SourcesDirectory)/signed/Microsoft.PowerShell.TextUtility
        # the certificate ID to use
        certificateId: "CP-460906"
        # The file pattern to use
        # If not using minimatch: comma separated, with * supported
        # If using minimatch: newline separated, with !, **, and * supported.
        # See link in the useMinimatch comments.
        pattern: 'Microsoft.PowerShell.*.dll,Microsoft.PowerShell.*.psd1,Microsoft.PowerShell.*.psm1'
        # decides if the task should use minimatch for the pattern matching.
        # https://github.com/isaacs/minimatch#features
        useMinimatch: false

    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: $(Build.SourcesDirectory)/signed/Microsoft.PowerShell.TextUtility
        Build_Repository_Uri: 'https://github.com/powershell/textutility'
        PackageName: 'Microsoft.PowerShell.TextUtility'
        PackageVersion: $(PackageVersion)

    - pwsh: |
        New-Item -Path $(Build.SourcesDirectory)/SignedZip -ItemType Directory -ErrorAction Ignore
        Compress-Archive -Path $(Build.SourcesDirectory)/signed/Microsoft.PowerShell.TextUtility -DestinationPath $(Build.SourcesDirectory)/SignedZip/Microsoft.PowerShell.TextUtility.zip -Force
      displayName: 'Compress archive'
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      inputs:
        targetpath: $(Build.SourcesDirectory)/signed/Microsoft.PowerShell.TextUtility
        artifactName: Signed

    - task: PublishPipelineArtifact@1
      inputs:
        targetpath: $(Build.SourcesDirectory)/SignedZip
        artifactName: SignedZip

- stage: compliance
  displayName: Compliance
  dependsOn: BuildAndSign
  jobs:
  - job: Compliance_Job
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure
    steps:
    - checkout: self
    - checkout: ComplianceRepo
    - download: current
      artifact: Signed

    - pwsh: |
        Get-ChildItem -Path "$(Pipeline.Workspace)\Signed" -Recurse
      displayName: Capture downloaded artifacts

    - template: assembly-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)\*.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance
        sourceScanPath: '$(Build.SourcesDirectory)'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        codeBaseName: 'TextUtility_20201120'
        # selections
        APIScan: false # set to false when not using Windows APIs.
