# release build
name: TextUtility-Release-$(Date:yyyyMMdd)$(Rev:.rr)
trigger: none

pr: none

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance
    ref: master

stages:
- stage: BuildAndSign
  displayName: Build and Sign
  pool:
    name: PowerShell1ES
    demands:
    - ImageOverride -equals PSMMS2019-Secure
  jobs:
  - job: 'BuildAndSign'
    displayName: Build and Sign
    variables:
    - group: ESRP
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        includePreviewVersions: true
        version: 6.x

    - pwsh: |
        Get-ChildItem -Path env:
      displayName: Capture environment
      condition: succeededOrFailed()

    - pwsh: |
        Set-Location "$(Build.SourcesDirectory)/TextUtility"
        Get-ChildItem -Recurse -File -Name | Write-Verbose -Verbose
        ./build.ps1
        Get-ChildItem -Recurse -File -Name | Write-Verbose -Verbose

      displayName: Execute Build

    - pwsh: |
        Set-Location "$(Build.SourcesDirectory)/TextUtility"
        $signSrcPath = "$(Build.SourcesDirectory)/TextUtility/out"
        # Set signing src path variable 
        $vstsCommandString = "vso[task.setvariable variable=signSrcPath]${signSrcPath}"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"

        $signOutPath = "$(Build.SourcesDirectory)/TextUtility/signed"
        $null = New-Item -ItemType Directory -Path $signOutPath
        # Set signing out path variable
        $vstsCommandString = "vso[task.setvariable variable=signOutPath]${signOutPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        # Set path variable for guardian codesign validation
        $vstsCommandString = "vso[task.setvariable variable=GDN_CODESIGN_TARGETDIRECTORY]${signOutPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        $packageVersion = ./build.ps1 -GetPackageVersion
        $vstsCommandString = "vso[task.setvariable variable=PackageVersion]$packageVersion"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"

      displayName: Setup variables for signing

    - publish: "$(Build.SourcesDirectory)/TextUtility/out/"
      artifact: out

      displayName: Publish unsigned module files

    - checkout: ComplianceRepo

    - template: EsrpSign.yml@ComplianceRepo
      parameters:
        # the folder which contains the binaries to sign
        buildOutputPath: $(signSrcPath)
        # the location to put the signed output
        signOutputPath: $(signOutPath)
        # the certificate ID to use
        certificateId: "CP-230012"
        # The file pattern to use
        # If not using minimatch: comma separated, with * supported
        # If using minimatch: newline separated, with !, **, and * supported.
        # See link in the useMinimatch comments.
        pattern: '*.dll,*.psd1,*.psm1,*.ps1xml'
        # decides if the task should use minimatch for the pattern matching.
        # https://github.com/isaacs/minimatch#features
        useMinimatch: false

    # 
    - pwsh: |
        $repoRoot = "$(Build.SourcesDirectory)/TextUtility"
        Set-Location $repoRoot
        Get-ChildItem -Path ${repoRoot} -File -Recurse | Out-String -Str | Write-Verbose -Verbose
        Copy-Item -Path "${repoRoot}/src/dictionary.txt" "${repoRoot}/signed/Microsoft.PowerShell.TextUtility"

      displayName: Copy dictionary.txt

    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: $(Build.SourcesDirectory)/TextUtility/signed/Microsoft.PowerShell.TextUtility
        Build_Repository_Uri: 'https://github.com/powershell/textutility'
        PackageName: 'Microsoft.PowerShell.TextUtility'
        PackageVersion: $(PackageVersion)

    - pwsh: |
        set-location $(Build.SourcesDirectory)/TextUtility
        ./build.ps1 -Package -Signed -NoBuild
        New-Item -Type Directory nupkg
        Copy-Item *.nupkg nupkg -ErrorAction Ignore -Verbose
        Get-ChildItem -Recurse -File -Name | out-string -str | Write-Verbose -Verbose

      displayName: Construct Signed Module with SBOM

    - pwsh: |
        New-Item -Path $(Build.SourcesDirectory)/TextUtility/SignedZip -ItemType Directory -ErrorAction Ignore
        Compress-Archive -Path $(Build.SourcesDirectory)/TextUtility/signed/Microsoft.PowerShell.TextUtility -DestinationPath $(Build.SourcesDirectory)/TextUtility/SignedZip/Microsoft.PowerShell.TextUtility.zip -Force

      displayName: 'Compress archive'
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      inputs:
        targetpath: $(Build.SourcesDirectory)/TextUtility/signed/Microsoft.PowerShell.TextUtility
        artifactName: Signed

    - task: PublishPipelineArtifact@1
      inputs:
        targetpath: $(Build.SourcesDirectory)/TextUtility/SignedZip
        artifactName: SignedZip

    - task: PublishPipelineArtifact@1
      inputs:
        targetpath: $(Build.SourcesDirectory)/TextUtility/nupkg
        artifactName: nupkg

- stage: compliance
  displayName: Compliance
  dependsOn: BuildAndSign
  jobs:
  - job: Compliance_Job
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure
    steps:
    - checkout: self
    - checkout: ComplianceRepo
    - download: current
      artifact: Signed

    - pwsh: |
        Get-ChildItem -Path "$(Pipeline.Workspace)\Signed" -Recurse

      displayName: Capture downloaded artifacts

    - template: assembly-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)\*.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance
        sourceScanPath: '$(Build.SourcesDirectory)'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        codeBaseName: 'textutility_202305'
        # selections
        APIScan: false # set to false when not using Windows APIs.
